steps:
# Build and deploy gateway
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherapp-gateway:$COMMIT_SHA', 'gateway']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/weatherapp-gateway:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/weather-gateway', 'gateway=gcr.io/${PROJECT_ID}/weatherapp-gateway:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

# Build and deploy geoservice
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherapp-geo-service:$COMMIT_SHA', 'geo-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/weatherapp-geo-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/geo-service-deployment', 'geo-service=gcr.io/${PROJECT_ID}/weatherapp-geo-service:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

# Build and deploy notification service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherapp-notification-service:$COMMIT_SHA', 'notification-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/weatherapp-notification-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/weather-notification-deployment', 'notification=gcr.io/${PROJECT_ID}/weatherapp-notification-service:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

# Build and deploy user service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherapp-user-service:$COMMIT_SHA', 'user-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/weatherapp-user-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/user-service-deployment', 'user-auth=gcr.io/${PROJECT_ID}/weatherapp-user-service:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

# Build and deploy weather service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherapp-weather-service:$COMMIT_SHA', 'weather-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/weatherapp-weather-service:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/weather-service-deployment', 'weather-service=gcr.io/${PROJECT_ID}/weatherapp-weather-service:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
