apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-gateway
  labels:
    app: weatherapp
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: gateway
        image: gcr.io/hd-weather/weatherapp-gateway:latest
        
        ports:
        - containerPort: 4000